//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forms
    {
        public System.Guid FormID { get; set; }
        public System.Guid ModuleID { get; set; }
        public string FormName { get; set; }
        public Nullable<int> FormLevel { get; set; }
        public string FormController { get; set; }
        public string FormView { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
