//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modules
    {
        public System.Guid ModuleID { get; set; }
        public string ModuleName { get; set; }
        public Nullable<int> ModuleLevel { get; set; }
        public Nullable<bool> NoSub { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
